server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_management?useSSL=false&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    storage_engine: innodb
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migration: true
    baseline-version: 0
